/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FertilizerShopManagementPackage;

import java.awt.print.PrinterException;
import javax.swing.table.TableModel;

/**
 *
 * @author Ramyadeepa
 */
public class PrintClass extends javax.swing.JFrame {

    /**
     * Creates new form PrintClass
     */
    public PrintClass() {
        initComponents();
    }
    String GrandTotal1;
    String PaidAmount1;
    String Balance1;
    
    public PrintClass(String GrandTotal,String PaidAmount,String Balance,TableModel TableModel1) throws PrinterException
    {
        initComponents();
        this.GrandTotal1=GrandTotal;
        this.PaidAmount1=PaidAmount;
        this.Balance1=Balance;
        jTextArea1.setText(jTextArea1.getText()+"*---------------------------------------------------------------------------------------------*\n");
        jTextArea1.setText(jTextArea1.getText()+"|-------------------------------------*-RVY Fertilizers-*-------------------------------------|\n");
        jTextArea1.setText(jTextArea1.getText()+"|---------------------------------------------------------------------------------------------|\n");
        jTextArea1.setText(jTextArea1.getText()+"|                                                                                             |\n");
        jTextArea1.setText(jTextArea1.getText()+"| Product Id           Product Name             Price              Quantity             Total |\n");
        for (int i=0;i<TableModel1.getRowCount();i++)
        {
            
            String ProductId=(String)TableModel1.getValueAt(i, 0);
            String ProductName=(String)TableModel1.getValueAt(i, 1);
            String ProductPrice=(String)TableModel1.getValueAt(i, 2);
            String ProductQuantity=(String)TableModel1.getValueAt(i, 3);
            String ProductTotal=(String)TableModel1.getValueAt(i, 4);
        jTextArea1.setText(jTextArea1.getText()     +ProductId          +ProductName        +ProductPrice      +ProductQuantity   +ProductTotal    );
        jTextArea1.setText(jTextArea1.getText()+"|                                                                                             |\n");
        jTextArea1.setText(jTextArea1.getText()+"|                            Grand Total"          +GrandTotal                              +"|\n");
        jTextArea1.setText(jTextArea1.getText()+"|                            Paid Amount"          +PaidAmount                              +"|\n");
        jTextArea1.setText(jTextArea1.getText()+"|                            Balance"              +Balance                                 +"|\n");
        jTextArea1.setText(jTextArea1.getText()+"|                                                                                             |\n");
        jTextArea1.setText(jTextArea1.getText()+"|---------------------------------------------------------------------------------------------|\n");
        jTextArea1.setText(jTextArea1.getText()+"|----------------------------------*-Thank You! Come Again!-*---------------------------------|\n");
        jTextArea1.setText(jTextArea1.getText()+"*---------------------------------------------------------------------------------------------*\n");
        jTextArea1.print();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
